// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CssController from "./css_controller"
application.register("css", CssController)

import CssFlipController from "./css_flip_controller"
application.register("css-flip", CssFlipController)

import TextController from "./text_controller"
application.register("text", TextController)
